jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      env:
        - secure: "bvF57xm+HS3tuZZk+nFiNeyozJXhtm3VwoyTetIZrDPX9Wr0UKnQkG7gze4au0yCQ6rQt8p39gOnY4e1h5JmlcdWlWjitd0XjCihKvQoTD2ZFE8teQVY8wQ0lbNIfAFm1x823KRCYfODt6V702T2tAIj38V3M5SHfm/EjIq9SkIKY1KrSG1WEPIgpimkI6Orl5R6082tIgtuZPhJqdjJZh2+5B/ImmcEkt7J4Cd6RL5W0P4bV76bzb6XLsBcyyIQskF+TpSshdeXwb3phwW5Fp9Ak3i+53HpLo/r6VrFiLrqQLBw+GXw64fegmRmWW4qOynbyeb58h9SYY7ULYuctgo+qux4mrkRIZoAJXmem2DVOSVblWsEwvu5H5FpLxXzOcypB5piTpmnCPd/OUw61vJp2Ez2Cr27xQ1wPdE+EIAd/gkJmxVECtLFvn8QTNio/hIaPXQdrUT2jriAEMFf/J9KcC9JKppTzESWxjmvC1+J4r/r+ujdp3KYy0W7v1/TzS19sa6VQmNR09+vkOfDoXrRPxkhGMpLkwE1LGQxxcZhGePuPKMPOQgkK3paxHue+SoIuCMfTZa3DDQHAHtA3NpEAMd4/TCFr3wnTyrsQc/eQpZ1ab1c5m14NAbAUdk9FSEQopOlkU4S7NAySN0rBm5Epspmo2LqbOVzDX0ssr8="
      script:
        - python hello_world.py
